name: "Qdrant"
description: "Qdrant is a vector similarity search engine and vector database"
version: "1.16"
slug: "qdrant"
arch:
  - aarch64
  - amd64
url: https://github.com/raphael1688dev/addon-qdrant
map:
  - type: addon_config
    read_only: False
    path: /qdrant/storage
legacy: False
host_network: False
ports:
  6333/tcp: 6333
  6334/tcp: 6334
options:
  http_port: 6333
  grpc_port: 6334
  cors_allow_origin: "*"
  log_level: "INFO"
  storage_path: "/qdrant/storage"
  env_vars: []
schema:
  http_port: port
  grpc_port: port
  cors_allow_origin: str
  log_level: list(DEBUG|INFO|WARN|ERROR)?
  storage_path: str?
  env_vars:
    - name: match(^[A-Z0-9_]+$)
      value: str
init: false
startup: service 
